name: Sync Files from Dropbox

on:
  schedule:
    - cron: '0 6 * * *'   # daily at 06:00 UTC (~08:00 Rome)
  workflow_dispatch:

# We use a PAT for pushing; this can stay read or be omitted.
permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with PAT)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}   # <- use your PAT for push perms
          ref: main

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone qpdf file

      # Set your Dropbox path under the *app folder* (no leading /)
      - name: Define Dropbox source path
        run: echo "SRC_PATH=Website/Documents" >> "$GITHUB_ENV"

      - name: Sync from Dropbox
        env:
          RCLONE_DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN_JSON }}
          RCLONE_DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          RCLONE_DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
        run: |
          rclone sync ":dropbox:${SRC_PATH}" "./docs" --fast-list -vv

      # Ensure PDFs are binary (no text filters/diffs)
      - name: Ensure .gitattributes for PDFs
        run: |
          {
            echo "*.pdf binary"
            echo "*.PDF binary"
          } > .gitattributes

      # Normalise/linearise PDFs and verify signatures & MIME
      - name: Normalise and verify PDFs
        run: |
          shopt -s nullglob globstar
          for f in docs/**/*.pdf docs/*.pdf docs/**/*.PDF docs/*.PDF; do
            qpdf --linearize "$f" "$f.qpdf" && mv -f "$f.qpdf" "$f"
            sig=$(hexdump -n 5 -v -e '/1 "%02X"' "$f" || true)
            mime=$(file -b --mime-type "$f" || true)
            echo "$f  sig=$sig  mime=$mime"
            if [ "$sig" != "255044462D" ] || [ "$mime" != "application/pdf" ]; then
              echo "::error::$f is not detected as a proper PDF"
              exit 1
            fi
          done

      - name: Commit and push changes (to main)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'Docs: Auto-sync from Dropbox'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          file_pattern: |
            .gitattributes
            docs
          add_options: '--all'

      # Prove the file is on the remote branch after push
      - name: Verify file on origin/main
        run: |
          git fetch origin main --depth=1
          git cat-file -e origin/main:docs/CV/KimTaveras_CV.pdf || (echo "::error::CV not on remote main"; exit 1)
          echo "OK: CV present on origin/main"
