name: Sync Files from Dropbox

on:
  schedule:
    - cron: '0 6 * * *'   # daily at 06:00 UTC (~08:00 Rome)
  workflow_dispatch:

permissions:
  contents: read   # we push using PAT

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main, with PAT)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT }}      # PAT must have Contents: Read & write

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone qpdf file

      - name: Define Dropbox source path
        run: echo "SRC_PATH=Website/Documents" >> "$GITHUB_ENV"

      - name: Remote listing (prove CV exists at source)
        env:
          RCLONE_DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN_JSON }}
          RCLONE_DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          RCLONE_DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
        run: |
          rclone lsl ":dropbox:${SRC_PATH}/CV/KimTaveras_CV.pdf" || (echo "::error::Remote CV missing (check path & case)"; exit 1)

      - name: rclone sync
        env:
          RCLONE_DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN_JSON }}
          RCLONE_DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          RCLONE_DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
        run: |
          rclone sync ":dropbox:${SRC_PATH}" "./docs" --fast-list -vv

      - name: Ensure .gitattributes for PDFs
        run: |
          {
            echo "*.pdf binary"
            echo "*.PDF binary"
          } > .gitattributes

      - name: Normalise and verify PDFs
        run: |
          shopt -s nullglob globstar
          for f in docs/**/*.pdf docs/*.pdf docs/**/*.PDF docs/*.PDF; do
            qpdf --linearize "$f" "$f.qpdf" && mv -f "$f.qpdf" "$f"
            sig=$(hexdump -n 5 -v -e '/1 "%02X"' "$f" || true)
            mime=$(file -b --mime-type "$f" || true)
            echo "$f  sig=$sig  mime=$mime"
            if [ "$sig" != "255044462D" ] || [ "$mime" != "application/pdf" ]; then
              echo "::error::$f is not detected as a proper PDF"
              exit 1
            fi
          done

      - name: Debug working tree
        run: |
          echo "---- ls docs ----"; ls -alR docs || true
          echo "---- git status ----"; git status --porcelain=v1
          echo "---- check-ignore ----"; git check-ignore -v docs/CV/KimTaveras_CV.pdf || true
          echo "---- remotes ----"; git remote -v

      - name: Commit changes (explicit)
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add -A docs .gitattributes
          git commit -m "Docs: Auto-sync from Dropbox" || echo "No changes to commit"

      - name: Push to main (explicit, with PAT)
        env:
          GH_TOKEN: ${{ secrets.PAT }}   # not used by git, but handy for other CLIs
        run: |
          git push origin HEAD:main

      - name: Verify CV on remote (origin/main)
        run: |
          git fetch origin main --depth=1
          git cat-file -e origin/main:docs/CV/KimTaveras_CV.pdf || (echo "::error::CV not on remote main"; exit 1)
          echo "OK: CV present on origin/main"
          git log -1 --stat -- docs/CV/KimTaveras_CV.pdf
