name: Sync Files from Dropbox

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone qpdf file

      - name: Sync files from Dropbox (App-Folder token; no leading /)
        env:
          RCLONE_DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN_JSON }}
          RCLONE_DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}         # your app key
          RCLONE_DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }} # your app secret
        run: |
          # Change this to match your folder under the app root
          SRC_PATH="Website/Documents"
          # (Optional) quick listing to help if path is wrong:
          rclone lsd ":dropbox:${SRC_PATH%/*}" || true
          rclone sync ":dropbox:${SRC_PATH}" "./docs" --fast-list

      # Ensure PDFs are binary (no text filters/diffs)
      - name: Ensure .gitattributes for PDFs
        run: |
          {
            echo "*.pdf binary"
            echo "*.PDF binary"
          } > .gitattributes

      # Normalise/linearise PDFs and verify signatures & MIME
      - name: Normalise and verify PDFs
        run: |
          shopt -s nullglob globstar
          for f in docs/**/*.pdf docs/*.pdf docs/**/*.PDF docs/*.PDF; do
            qpdf --linearize "$f" "$f.qpdf" && mv -f "$f.qpdf" "$f"
            sig=$(hexdump -n 5 -v -e '/1 "%02X"' "$f" || true)
            mime=$(file -b --mime-type "$f" || true)
            echo "$f  sig=$sig  mime=$mime"
            if [ "$sig" != "255044462D" ] || [ "$mime" != "application/pdf" ]; then
              echo "::error::$f is not detected as a proper PDF"
              exit 1
            fi
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Docs: Auto-sync from Dropbox'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          file_pattern: |
            .gitattributes
            docs
