name: Sync Files from Dropbox

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone qpdf

      - name: Configure rclone token for Dropbox
        run: |
          echo 'RCLONE_DROPBOX_TOKEN={"access_token":"${{ secrets.DROPBOX_ACCESS_TOKEN }}","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}' >> "$GITHUB_ENV"

      - name: Sync files from Dropbox (app-folder scope; no leading /)
        run: |
          rclone sync ":dropbox:Website/Documents" "./docs" --fast-list

      # Ensure GitHub treats PDFs as binary (prevents text render fallback)
      - name: Ensure .gitattributes for PDFs
        run: |
          echo "*.pdf binary" > .gitattributes
          echo "*.PDF binary" >> .gitattributes

      # Normalise PDFs so they start with %PDF- and are web-friendly
      - name: Normalise PDFs
        run: |
          shopt -s nullglob globstar
          for f in docs/**/*.pdf docs/*.pdf docs/**/*.PDF docs/*.PDF; do
            qpdf --linearize "$f" "$f.qpdf" && mv -f "$f.qpdf" "$f"
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Docs: Auto-sync from Dropbox'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          file_pattern: |
            .gitattributes
            docs
