name: Sync Files from Dropbox

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# allow pushes from github-actions[bot]
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone qpdf

      # Dropbox app is "App Folder" scoped; token must be JSON
      - name: Configure rclone token for Dropbox
        run: |
          echo 'RCLONE_DROPBOX_TOKEN={"access_token":"${{ secrets.DROPBOX_ACCESS_TOKEN }}","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}' >> "$GITHUB_ENV"

      - name: Sync files from Dropbox (paths are relative to the app folder)
        run: |
          rclone sync ":dropbox:Website/Documents" "./docs" --fast-list

      # Make PDFs web-friendly and ensure header starts with %PDF-
      - name: Normalise PDFs for GitHub preview
        run: |
          shopt -s nullglob globstar
          for f in docs/**/*.pdf docs/*.pdf; do
            hdr=$(hexdump -n 5 -v -e '/1 "%02X"' "$f" || true)
            if [ "$hdr" != "255044462D" ]; then
              echo "Rewriting nonstandard PDF header: $f"
            fi
            qpdf --linearize "$f" "$f.qpdf" && mv -f "$f.qpdf" "$f"
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Docs: Auto-sync from Dropbox'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          file_pattern: docs
